# This is a config for E2B sandbox template.
# You can use template ID (7y5gslsgy6mvfv166455) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("7y5gslsgy6mvfv166455") # Sync sandbox
# sandbox = await AsyncSandbox.create("7y5gslsgy6mvfv166455") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('7y5gslsgy6mvfv166455')

team_id = "446d15c5-ea0e-416c-9ecc-1e32f30bd9c3"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "7y5gslsgy6mvfv166455"
